### ISSUE TITLE
Agenda is not quite the word for this type of overview

### ISSUE THREAD

**Issue by nysthee** [brug-be/rubyshops#21]
We are a talking about 

> An agenda of Belgian Companies using Ruby

(in the project description).
I think the word overview or summary is better suited in this case. Suggestions are welcome!

**Comment by toch** [comment]
address book?

**Comment by gseerden** [comment]
list?

**Comment by nysthee** [comment]
I tend to like list more than address book.

**Comment by toch** [comment]
:+1: for list
