### ISSUE TITLE
Uniformize cities name

### ISSUE THREAD

**Issue by borisrorsvort** [brug-be/rubyshops#22]
No trolling but I think we should decide about standard for writing name to make it more searchable.
I suggest to use the flamish name if its in flanders, the french for wallonia and en for Brussels.

Any better suggestion ?

**Comment by toch** [comment]
Brussels being an exception, I would even add the FR and NL version.

Could you go over the list and check the names according your suggestion? and also add a note in the README.md about that? thanks!
