### ISSUE TITLE
Is this only for Belgium

### ISSUE THREAD

**Issue by ferdinandrosario** [brug-be/rubyshops#4]
Is this repo only for Belgium companies? If so then I would recommend it to make it Global, So that Rubyist around the world can refer more Ruby shops and this repo will be a great place to built another great ruby community.

**Comment by toch** [comment]
@ferdinandrosario yes for now, we focus on our local community. This is our first concern as a NGO. That's why for now, we'll list first Belgian companies. We accept also Dutch and Luxembourg companies.

If it works well, we'll think to expand it.

**Comment by ferdinandrosario** [comment]
Ok
